name: Solve Wordle

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - "main"

jobs:
  solve:
    runs-on: macos-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: create env file
        run: |
          touch .env
          echo TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} >> .env
          echo TWITTER_API_KEY_SECRET=${{ secrets.TWITTER_API_KEY_SECRET }} >> .env
          echo TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} >> .env
          echo TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }} >> .env

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Solve wordle
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: yarn solve
